### ISSUE TITLE
3.1版本播放音乐有杂音

### ISSUE THREAD

**Issue by wmcam** [BensonLaur/Beslyric-for-X#11]
你好，感谢你开源并分享这么好用的歌词制作软件，使用过程中发现3.1版本发现有很严重的杂音，同样的音乐在旧版上不会出现杂音，希望能够修复

**Comment by BensonLaur** [comment]
感谢反馈，我下载了windows版本下的 3.0 和 3.1 来再次对比了一下，3.1 版本本好像不会有严重杂音的情况。
相反地，其实在 3.0 的 1.5秒左右会有一个杂音，不过在 3.1 中修复了，会不会是看错版本了呢？ 或是 Mac下使用的吗（还没仔细测试mac下的情况）

**Comment by wmcam** [comment]
> 感谢反馈，我下载了windows版本下的3.0和3.1来再次对比了一下，3.1版本本好像不会有严重杂音的情况。
> 相反地​​，其实在3.0的1.5秒左右会有一个杂音，不过在3.1中修复了，会不会是看错版本了呢？或是Mac下使用的吗（还没仔细测试mac下的情况）

试了其他歌曲不会出现杂音，可能那首音乐的问题，开始我是下载BesLyric2.2.4版本，载入音乐那首音乐没出现任何杂音，但编辑完成后软件崩溃了，发现有新版本就下载了最新的3.1，播放那首音乐就会出现很大的杂音，刚才又试了其他音乐不会出现任何杂音，所以应该是那首音乐的编码比较特别或者损坏了，我是WINDOWS10系统的，感谢你的解答。

**Comment by BensonLaur** [comment]
原来如此
