### ISSUE TITLE
对于播放条的修改出错

### ISSUE THREAD

**Issue by pzhlkj6612** [BensonLaur/Beslyric-for-X#13]
抱歉。我在 #12 中对 sliderSong 的 seek 相关代码修改有错，导致 sliderSong 和 labelTimeCurrent 的功能出现问题。

重现：

```git checkout 9827fabc294a08533d01c83e27122fbc99475664```。

不播放任何歌曲，拖动并释放 sliderSong ， sliderSong 回到起始位置， labelTimeCurrent 为 -35791:-23.-648 ，表示拿到了没有初始化的 position ；日志输出 ```positionChanged(int position= -2147483648 )``` ，表示 m_positionUpdateTimer 已在工作。

---

对比：

```git checkout d33f89a93a279d43c76f0237b738fdb5d2d2de4a``` 回到前一个提交，并在 ```void BottomWidget::positionChanged(int position)``` 方法下添加 ```qDebug()<<"void BottomWidget::positionChanged(int position= "<<position<<" )";``` 。

不播放任何歌曲，拖动并释放 sliderSong ， sliderSong 停留在释放时的位置， labelTimeCurrent 为 00:00.000 ，不输出 ```positionChanged(int position)``` ，表示 m_positionUpdateTimer 没有工作。

---

我将尽快修复。

**Comment by pzhlkj6612** [comment]
在 ```void BottomWidget::positionChanged(int position)``` 方法中输出日志，发现在歌曲播放结束后，m_positionUpdateTimer 仍然在工作，这是之前就存在的问题，也需要做修复。

**Comment by BensonLaur** [comment]
😁 我之前简单测试了一下好像也没有能发现问题

**Comment by pzhlkj6612** [comment]
发现更多问题。由于在 9827fabc294a08533d01c83e27122fbc99475664 中的修改不完整，在播放时单击或长按 sliderSong（不拖动），可能会使 sliderSong 回退到之前的某个时刻。

**Comment by pzhlkj6612** [comment]
> 在播放时单击或长按 sliderSong（不拖动），可能会使 sliderSong 回退到之前的某个时刻。

这是由 sliderSong.value 精度不够导致的。

**Comment by pzhlkj6612** [comment]
#15 、 #16 已解决上述问题。
