### ISSUE TITLE
编译时出现未找到SDL.h

### ISSUE THREAD

**Issue by zys2001121** [BensonLaur/Beslyric-for-X#24]
在ArchLinux上编译时出现找不到SDL.h

**Comment by BensonLaur** [comment]
这个开发环境下的话，仅在Ubuntu发新版测试过。你有没有下载这个项目另一个依赖项目呢

**Comment by BensonLaur** [comment]
这个开发环境下的话，仅在Ubuntu发行版测试过。你有没有下载这个项目另一个依赖项目呢

**Comment by zys2001121** [comment]
已解决 在arch下，SDL.h在/usr/include/SDL2目录下 手动添加至到pro文件即可
但在链接时出现了找不到ffmpeg的相关.so库的情况 原因可能是因为arch使用/usr/lib而非/usr/local/lib
