### ISSUE TITLE
添加对 Flac 后缀名文件支持

### ISSUE THREAD

**Issue by iMusynx** [BensonLaur/Beslyric-for-X#6]
因为是 ffmpeg 编码器进行解码，是否可以对 Flac 文件的支持？
实测在不转换编码只是简单更改后缀名之后，可以正常解码文件。

**Comment by BensonLaur** [comment]
这个可以考虑，没有开放的想法是初步想着beslyric 只用来制作网易云音乐的歌词，然后觉得网易云下载下来的只有MP3，所以初步就觉得够了。不过还是可以考虑让用户选择任意文件来尝试播放的。

**Comment by pzhlkj6612** [comment]
Related commit: https://github.com/Beslyric-for-X/Beslyric-for-X/commit/675e0118143a6852b45be0533457d249ff73fbf2
