### ISSUE TITLE
从歌词单到歌词预览界面切换步骤太繁琐

### ISSUE THREAD

**Issue by binsee** [BensonLaur/Beslyric-for-X#7]
## 场景说明
* 要预览制作好的lrc歌词

## 操作步骤
1. 点击进入 **歌词单** 功能
2. 在 **歌词单列表** 中双击一首歌曲播放
3. 点击右上角按钮切换回主界面
4. 点左下角歌曲封面进入歌曲播放界面，预览歌词

![1](https://user-images.githubusercontent.com/5285894/52457075-f3fa5680-2b92-11e9-8c95-23f45dbb854c.gif)

## 问题说明
从歌词单界面播放歌曲到查看到歌词，操作繁琐。界面上虽然尽量和网易云音乐保持风格一致，但考虑到这款工具只用来制作歌词，可以认为工具只有三个功能：
1. 下载歌曲、歌词
2. 制作歌词
3. 播放歌曲并预览歌词

而查看歌词单到预览歌词是个关联性很强的操作，应当减少切换界面导致的操作步骤，用着会更舒服一些。

## 建议方案

可以考虑在歌词界面时，左下角仍然保持歌曲区域显示，可以直接点击歌曲封面切换到预览歌词

![image](https://user-images.githubusercontent.com/5285894/52457325-248ec000-2b94-11e9-8dc5-50da0497b3ef.png)

**Comment by binsee** [comment]
## 另一种方案：
将歌词单仿照云音乐的歌词单栏，即：
* 将歌词单界面左侧的列表移动到主界面左侧列表中
* **制作记录** 与 **创建的歌词单** 栏与 **制作歌词** 、 **下载歌曲** 、 **下载歌词** 三项一样作为一级选项，功能切换上会更便捷

或者： **制作记录** 这个特殊的歌词单，可以像云音乐的 `我喜欢的音乐` 一样，作为一个特殊的子列表，存在于歌词单主选项下。其他歌词单，与 **制作记录** 同级。

**Comment by BensonLaur** [comment]
确实切换页面操作有点不方便，这个会结合建议考虑改进一下

**Comment by binsee** [comment]
😄 期待
