### ISSUE TITLE
不支持拖动以改变播放进度

### ISSUE THREAD

**Issue by binsee** [BensonLaur/Beslyric-for-X#8]
不支持拖动进度栏以改变播放进度，使用上有些不便，希望可以改进。

![image](https://user-images.githubusercontent.com/5285894/52457410-8c450b00-2b94-11e9-9894-cb16d4419003.png)

**Comment by BensonLaur** [comment]
现在进度条的拖动在制作歌词过程模式下故意限制不能拖动，在其他情况则可以（不过此时拖动需要鼠标按住圆圈）。整体来说，这一点应该算是功能存在误导性，会考虑做相关改进

**Comment by binsee** [comment]
播放歌曲时确实可以拖动小圆点改变进度。
期待改进

**Comment by pzhlkj6612** [comment]
> 现在进度条的拖动在制作歌词过程模式下故意限制不能拖动，在其他情况则可以（不过此时拖动需要鼠标按住圆圈）。整体来说，这一点应该算是功能存在误导性，会考虑做相关改进

就“制作歌词时不能拖动以改变进度”来说，如果能将手柄隐藏，可能会让用户更容易理解一些。
