### ISSUE TITLE
希望支持切换文件名命名格式

### ISSUE THREAD

**Issue by binsee** [BensonLaur/Beslyric-for-X#9]
一直习惯使用 `歌手 - 歌曲名` 的格式保存歌曲，而此工具默认为 `歌曲名 - 歌手` 的格式，且不支持切换。
因此有些不合习惯，希望可以增加选项以支持切换命名格式。

网易云音乐设置中的 `音乐命名格式` 选项：
![image](https://user-images.githubusercontent.com/5285894/52457498-0d040700-2b95-11e9-8896-e4fc286f197f.png)

**Comment by BensonLaur** [comment]
这个可以有

**Comment by binsee** [comment]
😄
